version: '3.4'

services:
  courseenrollmentapi:
    image: ${DOCKER_REGISTRY-}courseenrollmentapi
    build:
      context: .
      dockerfile: CourseEnrollmentApi\Dockerfile
    depends_on:
    - db
  db:
    image: "microsoft/mssql-server-windows-express"
    environment:
        SA_PASSWORD: "C0urseEnr011ment"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"